export const CakeList = [
  {
    id: 1,
    type: 'Cake',
    Enname: 'Classic Cream Cake',
    Koname: '클래식 크림 케이크',
    detail: '치즈본 시그니쳐 크림 삼단 케이크',
    date: '2023-06-25',
    price: '150,000',
    img: '/assets/Cakeassets/ChocoClassiccake.jpg',
  },
  {
    id: 2,
    type: 'Cake',
    Enname: 'Chocolate Fudge Cakes',
    Koname: '초콜릿 퍼지 케이크',
    detail:
      '부드러운 초코크림에 초코칩 토핑으로 더욱 깊은 초코맛을 즐길 수 있는 삼단 케이크',
    date: '2023-06-25',
    price: '150,000',
    img: '/assets/Cakeassets/ChocolateFudgeCake.jpg',
  },
  {
    id: 3,
    type: 'Cake',
    Enname: 'Fig Dome Cake',
    Koname: '무화과 돔 케이크',
    detail: '무화과와 치즈본 시그니쳐 크림 돔 케이크',
    date: '2023-06-25',
    price: '45,000',
    image: '/assets/Cakeassets/FigDomeCake.jpg',
  },
  {
    id: 4,
    type: 'Cake',
    Enname: 'Lemon Earl Grey Cake',
    Koname: '레몬 얼그레이 케이크',
    detail: '상큼한 레몬과 얼그레이가 조화로운 삼단 케이크',
    date: '2023-06-25',
    price: '150,000',
    image: '/assets/Cakeassets/LemonEarlGreyCake.jpg',
  },
  {
    id: 5,
    type: 'Cake',
    Enname: 'Meringue Strawberry Cake',
    Koname: '머랭 스토로베리 케이크',
    detail: '살살 녹는 머랭과 상큼한 딸기가 만난 삼단 케이크',
    date: '2023-06-25',
    price: '150,000',
    image: '/assets/Cakeassets/MeringueStrawberryShortcake.jpg',
  },
  {
    id: 6,
    type: 'Cake',
    Enname: 'Milk Cream Cake',
    Koname: '우유 생크림 케이크',
    detail: '우유맛이 가득한 삼단 생크림 케이크',
    date: '2023-06-25',
    price: '180,000',
    image: '/assets/Cakeassets/ChocoClassiccake.jpg',
  },
  {
    id: 7,
    type: 'Cake',
    Ename: 'Mint Choco Dome Cake',
    Koname: '민트초코 돔 케이크',
    detail: '민트와 초코가 만난 돔 케이크',
    date: '2023-06-25',
    price: '45,000',
    image: '/assets/Cakeassets/MintChocoDomeCake.jpg',
  },
  {
    id: 8,
    type: 'Cake',
    Enname: 'MixBerry Cake',
    Koname: '믹스베리 케이크',
    detail: '블루베리, 라즈베리, 크랜베리, 스트로베리가 들어간 삼단 케이크',
    date: '2023-06-25',
    price: '170,000',
    image: '/assets/Cakeassets/MixBerryCake.jpg',
  },
  {
    id: 9,
    type: 'Cake',
    Enname: 'Red Velevet Cream Cake',
    Koname: '레드벨벳 크림 케이크',
    detail: '레드벨벳과 크림치즈로 가득한 사단 케이크',
    date: '2023-06-25',
    price: '230,000',
    image: '/assets/Cakeassets/RedVelevetCreamcheeseFrostingCake.jpg',
  },
  {
    id: 10,
    type: 'Cake',
    Enname: 'Victoria Sponge Cake',
    Koname: '빅토리아 스펀지 케이크',
    detail: '스트로베리 잼이 들어간 삼단 케이크',
    date: '2023-06-25',
    price: '150,000',
    image: '/assets/Cakeassets/VictoriaSpongeCake.jpg',
  },
  {
    id: 1,
    type: 'Fingercake',
    Enname: 'Berry Pistachio Finger Cake',
    Koname: '스토로베리 피스타치오 핑거 케이크',
    detail: '상큼한 딸기와 담백한 피스타치오가 만난 핑거 케이크 ',
    date: '2023-06-25',
    price: '150,000',
    piece: 30,
    image: '/assets/Cupcakeassets/BerryPistachioFingercake.jpg',
  },
  {
    id: 2,
    type: 'Cupcake',
    Enname: 'Caramel Chocolate CupCake',
    Koname: ' 카라멜 초콜릿 컵케이크',
    detail: '초코칩이 들어간 카라멜 컵케이크 ',
    date: '2023-06-25',
    price: '100,000',
    piece: 30,
    image: '/assets/Cupcakeassets/CaramelChocolateCupCake.jpg',
  },
  {
    id: 3,
    type: 'Fingercake',
    Enname: 'Cherry Choco Finger Cake',
    Koname: ' 체리 초코 핑거 케이크',
    detail:
      '초코 베이스에 생 체리와 치즈본 시그니쳐인 체리 크림이 들어간 핑거 케이크 ',
    date: '2023-06-25',
    price: '110,000',
    piece: 30,
    image: '/assets/Cupcakeassets/cherryChocoFingerCake.jpg',
  },
  {
    id: 4,
    type: 'Fingercake',
    Enname: 'Classic Vanilla Finger Cake',
    Koname: '클래식 바닐라 핑거 케이크',
    detail: '바닐라 빈이 씹히는 클래식 핑거 케이크',
    date: '2023-06-25',
    price: '110,000',
    piece: 30,
    image: '/assets/Cupcakeassets/ClassicVailaFingerCake.jpg',
  },
  {
    id: 5,
    type: 'Fingercake',
    Enname: 'Lemon Finger Cake',
    Koname: '레몬 핑거 케이크',
    detail: '레몬 크림과 슬라이스 레몬이 씹히는 상큼한 핑거 케이크',
    date: '2023-06-25',
    price: '120,000',
    piece: 30,
    image: '/assets/Cupcakeassets/LemonFingerCake.jpg',
  },
  {
    id: 6,
    type: 'Cupcake',
    Enname: 'Milk Cream CupCake',
    Koname: '우유 생크림 컵케이크',
    detail: '우유맛이 가득한 삼단 생크림 컵케이크',
    date: '2023-06-25',
    price: '100,000',
    piece: 30,
    image: '/assets/Cupcakeassets/MilkCreamCupCake.jpg',
  },
  {
    id: 7,
    type: 'Cupcake',
    Enname: 'Orange Cheddar Cheese CupCake',
    Koname: '오렌지 체다치즈 컵케이크',
    detail: '짭짤한 체다와 상큼한 오렌지가 만난 컵케이크',
    date: '2023-06-25',
    price: '120,000',
    piece: 30,
    image: '/assets/Cupcakeassets/OrangeCheddarCupCake.jpg',
  },
  {
    id: 8,
    type: 'Fingercake',
    Enname: 'Fig Red Velevet Finger Cake',
    Koname: '무화과 레드벨벳 핑거 케이크',
    detail: '무화과와 레드벨벳이 만난 핑거 케이크',
    date: '2023-06-25',
    price: '120,000',
    piece: 30,
    image: '/assets/Cupcakeassets/RedVeleteFingerCake.jpg',
  },
  {
    id: 9,
    type: 'Cupcake',
    Enname: 'Strawberry CupCake',
    Koname: '스트로베리 컵케이크',
    detail: '클래식 스트로베리 컵케이크',
    date: '2023-06-25',
    price: '100,000',
    piece: 30,
    image: '/assets/Cupcakeassets/StrawberryCupCake.jpg',
  },
  {
    id: 10,
    type: 'Fingercake',
    Enname: 'Victoria Sponge Finger Cake',
    Koname: '빅토리아 스펀지 핑거 케이크',
    detail: '생 딸기와 잼이 들어간 핑거 케이크',
    date: '2023-06-25',
    price: '120,000',
    piece: 30,
    image: '/assets/Cupcakeassets/VictoriaSpongeFingerCake.jpg',
  },
];
